name: colorist
description: "Flutter code generator for custom-named color palettes."
repository: https://github.com/tara-pogancev/flutter-colorist
issue_tracker: https://github.com/tara-pogancev/flutter-colorist/issues
version: 0.0.1cd ..

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0
  colorist_annotations: ^0.0.1
  shared_preferences: ">=2.4.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.9.0
  colorist_builder: ^0.0.1
