name: example
description: An example Flutter project featuring the package Colorist Gen.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  colorist:
    path: ../
  freezed: ^3.2.4
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.9.0
  colorist_builder:
    path: ../../colorist_builder/
  json_serializable: ^6.11.3

flutter:
  uses-material-design: true

  assets:
    - assets/
